FROM ubuntu:trusty

MAINTAINER 17764563720@163.com



RUN apt-get update

RUN apt-get install -y python3.6
RUN apt-get install -y python-dev
RUN apt-get install -y python-pip
#RUN pip3 install pip -U \
# 用完包管理器后安排打扫卫生可以显著的减少镜像大小
RUN apt-get clean
RUN apt-get autoclean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# 配置默认放置 App 的目录
RUN mkdir -p /app
WORKDIR /app
EXPOSE 80
CMD ["bash"]