"""重新建表

Revision ID: d1b1197d19d5
Revises: 
Create Date: 2020-05-05 14:28:18.164147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b1197d19d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_info_email'), 'user_info', ['email'], unique=True)
    op.create_index(op.f('ix_user_info_username'), 'user_info', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user_info.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user_info.id'], )
    )
    op.create_table('post_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_form_timestamp'), 'post_form', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_form_timestamp'), table_name='post_form')
    op.drop_table('post_form')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_info_username'), table_name='user_info')
    op.drop_index(op.f('ix_user_info_email'), table_name='user_info')
    op.drop_table('user_info')
    # ### end Alembic commands ###
